version: '3'

services:
  app:
    container_name: robot-manager-${DRONE_BUILD_NUMBER}
    image: hub2.godd.site:7443/server/robot-manager:${DRONE_BUILD_NUMBER}
    restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.robot-manager.entrypoints=https
      - traefik.http.routers.robot-manager.rule=Host(`rm.godd.site`)
      - traefik.http.routers.robot-manager.middlewares=dash-compress@file
      - traefik.http.routers.robot-manager.tls=true
      - traefik.http.routers.robot-manager.tls.certresolver=myresolver
      - traefik.http.routers.robot-manager.tls.domains[0].main=godd.site
      - traefik.http.routers.robot-manager.tls.domains[0].sans=*.godd.site

networks:
  traefik:
    external: true